
#compose-команда
#yml-расширение файла docker
version: "3.9"
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=tg-bot_db
      - POSTGRES_USER=par
      - POSTGRES_PASSWORD=sasha2283536Q
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5429:5432"
volumes:
  db: